import { Router, type IRouter } from "express";
import healthRouter from "./health";
import accountAuthRouter from "./accountAuth";
import accountAdminRouter from "./accountAdmin";
import authRouter from "./auth";
import claimsRouter from "./claims";
import auditRouter from "./audit";
import settingsRouter from "./settings";
import emailRouter from "./email";
import storageRouter from "./storage";
import documentsRouter from "./documents";
import ingestRouter from "./ingest";
import dashboardRouter from "./dashboard";
import carriersRouter from "./carriers";
import downloadRouter from "./download";
import jobsRouter from "./jobs";
import workflowRouter from "./workflow";
import platformTenantAccessRouter from "./platformTenantAccess";
import platformCarriersRouter from "./platformCarriers";

const router: IRouter = Router();

router.use(healthRouter);
router.use(accountAuthRouter);
router.use(authRouter);
router.use(platformTenantAccessRouter);
router.use(platformCarriersRouter);
router.use(accountAdminRouter);
router.use(dashboardRouter);
router.use(claimsRouter);
router.use(auditRouter);
router.use(settingsRouter);
router.use(emailRouter);
router.use(storageRouter);
router.use(documentsRouter);
router.use(ingestRouter);
router.use(carriersRouter);
router.use(downloadRouter);
router.use(jobsRouter);
router.use(workflowRouter);

export default router;
